#!/usr/bin/env python3
"""
Generate include/ark/kconfig.h from .kconfig (simple key=value).
This is intentionally tiny and does not implement Linux Kconfig syntax.
"""

from __future__ import annotations

import os
import sys


DEFAULTS: dict[str, str] = {
    "ARCH": "x86",
    "INIT_BIN": "/init.bin",
    "PRINTK_ENABLE": "1",
    "USB_ENABLE": "1",
    "AUDIO_ENABLE": "1",
    "NET_ENABLE": "1",
    "DEBUG_VERBOSE": "0",
    "FB_ENABLE": "1",
    "FB_WIDTH": "1024",
    "FB_HEIGHT": "768",
    "FB_BPP": "32",
}


def _c_string(s: str) -> str:
    return '"' + s.replace("\\", "\\\\").replace('"', '\\"') + '"'


def read_kv(path: str) -> dict[str, str]:
    cfg = dict(DEFAULTS)
    if not os.path.exists(path):
        return cfg
    with open(path, "r", encoding="utf-8", errors="replace") as f:
        for raw in f:
            line = raw.strip()
            if not line or line.startswith("#"):
                continue
            if "=" not in line:
                continue
            k, v = line.split("=", 1)
            k = k.strip()
            v = v.strip()
            if not k:
                continue
            cfg[k] = v
    return cfg


def main() -> int:
    if len(sys.argv) != 3:
        print("usage: gen_kconfig_h.py <.kconfig> <out_header>", file=sys.stderr)
        return 2

    in_path = sys.argv[1]
    out_path = sys.argv[2]

    cfg = read_kv(in_path)
    arch = cfg.get("ARCH", "x86").strip()

    lines: list[str] = []
    lines.append("/* Auto-generated by scripts/gen_kconfig_h.py. DO NOT EDIT. */")
    lines.append("#pragma once")
    lines.append("")

    # Base values
    lines.append(f"#define CONFIG_ARCH {_c_string(arch)}")
    lines.append(f"#define CONFIG_INIT_BIN {_c_string(cfg.get('INIT_BIN', '/init.bin'))}")
    lines.append(f"#define CONFIG_PRINTK_ENABLE {int(cfg.get('PRINTK_ENABLE', '1') or '0')}")
    lines.append(f"#define CONFIG_USB_ENABLE {int(cfg.get('USB_ENABLE', '1') or '0')}")
    lines.append(f"#define CONFIG_AUDIO_ENABLE {int(cfg.get('AUDIO_ENABLE', '1') or '0')}")
    lines.append(f"#define CONFIG_NET_ENABLE {int(cfg.get('NET_ENABLE', '1') or '0')}")
    lines.append(f"#define CONFIG_DEBUG_VERBOSE {int(cfg.get('DEBUG_VERBOSE', '0') or '0')}")
    lines.append(f"#define CONFIG_FB_ENABLE {int(cfg.get('FB_ENABLE', '1') or '0')}")
    lines.append(f"#define CONFIG_FB_WIDTH {int(cfg.get('FB_WIDTH', '1024') or '0')}")
    lines.append(f"#define CONFIG_FB_HEIGHT {int(cfg.get('FB_HEIGHT', '768') or '0')}")
    lines.append(f"#define CONFIG_FB_BPP {int(cfg.get('FB_BPP', '32') or '0')}")
    lines.append("")

    # Arch convenience toggles
    for a in ("x86", "x86_64", "arm", "riscv"):
        name = a.upper().replace("-", "_")
        lines.append(f"#define CONFIG_ARCH_{name} {1 if arch == a else 0}")
    lines.append("")

    os.makedirs(os.path.dirname(out_path), exist_ok=True)
    with open(out_path, "w", encoding="utf-8") as f:
        f.write("\n".join(lines) + "\n")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())

