#!/usr/bin/env python3
"""
Generate include/ark/kconfig.h from .kconfig (simple key=value format).
Handles the full expanded Ark menuconfig option set.
"""

from __future__ import annotations
import os, sys

# ------------------------------------------------------------------
# Default values — match apply_defconfig() in menuconfig.c
# ------------------------------------------------------------------
DEFAULTS: dict[str, str] = {
    # Architecture
    "ARCH": "x86_64",
    "BITS": "64",
    "CODENAME": "affectionate cat",
    # Build
    "OPT_LEVEL": "2",
    "DEBUG": "0",
    "WERROR": "0",
    # Userspace
    "INIT_BIN": "/init.bin",
    "BUILD_INIT": "0",
    # Printk / Serial
    "PRINTK_ENABLE": "1",
    "SERIAL_ENABLE": "1",
    "SERIAL_PORT": "0x3F8",
    "LOGLEVEL": "4",
    # Memory
    "PMM_ENABLE": "1",
    "VMM_ENABLE": "1",
    "HEAP_SIZE_KB": "4096",
    "STACK_SIZE_KB": "64",
    # Framebuffer
    "FB_ENABLE": "1",
    "FB_WIDTH": "1024",
    "FB_HEIGHT": "768",
    "FB_BPP": "32",
    "FB_DRIVER": "bga",
    # I/O
    "PIO_ENABLE": "1",
    "MMIO_ENABLE": "1",
    "IOAPIC_ENABLE": "1",
    "PIC_ENABLE": "1",
    # Interrupts
    "IDT_ENABLE": "1",
    "IRQ_STACK": "1",
    "NMI_ENABLE": "1",
    # USB
    "USB_ENABLE": "1",
    "USB_XHCI": "1",
    "USB_EHCI": "1",
    "USB_UHCI": "0",
    "USB_HID": "1",
    # Storage
    "ATA_ENABLE": "1",
    "SATA_ENABLE": "1",
    "SD_ENABLE": "1",
    "FAT32_ENABLE": "1",
    "RAMFS_ENABLE": "1",
    "VFS_ENABLE": "1",
    "ZIP_ENABLE": "1",
    "ATA_DMA": "1",
    # Networking
    "NET_ENABLE": "1",
    "E1000_ENABLE": "1",
    "E100_ENABLE": "0",
    "IP_ENABLE": "1",
    "UDP_ENABLE": "1",
    "TCP_ENABLE": "0",
    # Audio
    "AUDIO_ENABLE": "1",
    "AC97_ENABLE": "1",
    "HDA_ENABLE": "0",
    # HID
    "KBD_ENABLE": "1",
    "MOUSE_ENABLE": "1",
    "TOUCH_ENABLE": "0",
    # GPU
    "GPU_ENABLE": "1",
    "VESA_ENABLE": "1",
    # PCI
    "PCI_ENABLE": "1",
    "PCI_PROBE_ALL": "1",
    # Scheduler
    "SCHED_ENABLE": "1",
    "SCHED_PREEMPT": "1",
    "SCHED_TIMESLICE_MS": "10",
    # Syscalls
    "SYSCALL_ENABLE": "1",
    "ELF_LOADER": "1",
    # Debug
    "DEBUG_VERBOSE": "0",
    "DEBUG_KASAN": "0",
    "DEBUG_PANIC_DUMP": "1",
    # QEMU
    "QEMU_RAM_MB": "256",
    "QEMU_SMP": "1",
    "QEMU_NET": "1",
    "QEMU_USB": "1",
    "QEMU_NOGRAPHIC": "0",
}


def _str(s: str) -> str:
    return '"' + s.replace("\\", "\\\\").replace('"', '\\"') + '"'


def _bool(cfg: dict, key: str) -> int:
    v = cfg.get(key, DEFAULTS.get(key, "0"))
    try:
        return 1 if int(v, 0) else 0
    except (ValueError, TypeError):
        return 1 if v.lower() in ("y", "yes", "true", "1") else 0


def _int(cfg: dict, key: str, default: int = 0) -> int:
    v = cfg.get(key, DEFAULTS.get(key, str(default)))
    try:
        return int(v, 0)
    except (ValueError, TypeError):
        return default


def read_kv(path: str) -> dict[str, str]:
    cfg = dict(DEFAULTS)
    if not os.path.exists(path):
        return cfg
    with open(path, encoding="utf-8", errors="replace") as f:
        for raw in f:
            line = raw.strip()
            if not line or line.startswith("#"):
                continue
            if "=" not in line:
                continue
            k, v = line.split("=", 1)
            k, v = k.strip(), v.strip()
            if k:
                cfg[k] = v
    return cfg


def main() -> int:
    if len(sys.argv) != 3:
        print("usage: gen_kconfig_h.py <.kconfig> <out_header>", file=sys.stderr)
        return 2

    cfg = read_kv(sys.argv[1])
    arch = cfg.get("ARCH", "x86").strip()
    bits_raw = cfg.get("BITS", "32").strip()
    if arch == "x86_64" and bits_raw not in ("32", "64"):
        bits_raw = "64"
    bits = int(bits_raw) if bits_raw in ("32", "64") else 32

    L: list[str] = []
    L += [
        "/* Auto-generated by scripts/gen_kconfig_h.py — DO NOT EDIT. */",
        "#pragma once",
        "",
        "/* ---- Architecture ---- */",
    ]
    L.append(f"#define CONFIG_ARCH        {_str(arch)}")
    L.append(f"#define CONFIG_BITS        {bits}")
    L.append(f"#define CONFIG_32BIT       {1 if bits == 32 else 0}")
    L.append(f"#define CONFIG_64BIT       {1 if bits == 64 else 0}")
    for a in ("x86", "x86_64", "arm", "riscv"):
        L.append(f"#define CONFIG_ARCH_{a.upper().replace('-','_'):<10} {1 if arch == a else 0}")

    L += ["", "/* ---- Build ---- */"]
    L.append(f"#define CONFIG_OPT_LEVEL   {_int(cfg, 'OPT_LEVEL', 2)}")
    L.append(f"#define CONFIG_DEBUG       {_bool(cfg, 'DEBUG')}")
    L.append(f"#define CONFIG_WERROR      {_bool(cfg, 'WERROR')}")
    L.append(f"#define CONFIG_INIT_BIN    {_str(cfg.get('INIT_BIN', '/init.bin'))}")
    L.append(f"#define CONFIG_CODENAME    {_str(cfg.get('CODENAME', 'ark'))}")

    L += ["", "/* ---- Printk / Serial ---- */"]
    L.append(f"#define CONFIG_PRINTK_ENABLE   {_bool(cfg, 'PRINTK_ENABLE')}")
    L.append(f"#define CONFIG_SERIAL_ENABLE   {_bool(cfg, 'SERIAL_ENABLE')}")
    L.append(f"#define CONFIG_SERIAL_PORT     {_int(cfg, 'SERIAL_PORT', 0x3F8)}")
    L.append(f"#define CONFIG_LOGLEVEL        {_int(cfg, 'LOGLEVEL', 4)}")

    L += ["", "/* ---- Memory ---- */"]
    L.append(f"#define CONFIG_PMM_ENABLE      {_bool(cfg, 'PMM_ENABLE')}")
    L.append(f"#define CONFIG_VMM_ENABLE      {_bool(cfg, 'VMM_ENABLE')}")
    L.append(f"#define CONFIG_HEAP_SIZE_KB    {_int(cfg, 'HEAP_SIZE_KB', 4096)}")
    L.append(f"#define CONFIG_STACK_SIZE_KB   {_int(cfg, 'STACK_SIZE_KB', 64)}")

    L += ["", "/* ---- Framebuffer ---- */"]
    L.append(f"#define CONFIG_FB_ENABLE   {_bool(cfg, 'FB_ENABLE')}")
    L.append(f"#define CONFIG_FB_WIDTH    {_int(cfg, 'FB_WIDTH', 1024)}")
    L.append(f"#define CONFIG_FB_HEIGHT   {_int(cfg, 'FB_HEIGHT', 768)}")
    L.append(f"#define CONFIG_FB_BPP      {_int(cfg, 'FB_BPP', 32)}")
    L.append(f"#define CONFIG_FB_DRIVER   {_str(cfg.get('FB_DRIVER', 'bga'))}")

    L += ["", "/* ---- I/O ---- */"]
    L.append(f"#define CONFIG_PIO_ENABLE      {_bool(cfg, 'PIO_ENABLE')}")
    L.append(f"#define CONFIG_MMIO_ENABLE     {_bool(cfg, 'MMIO_ENABLE')}")
    L.append(f"#define CONFIG_IOAPIC_ENABLE   {_bool(cfg, 'IOAPIC_ENABLE')}")
    L.append(f"#define CONFIG_PIC_ENABLE      {_bool(cfg, 'PIC_ENABLE')}")

    L += ["", "/* ---- Interrupts ---- */"]
    L.append(f"#define CONFIG_IDT_ENABLE  {_bool(cfg, 'IDT_ENABLE')}")
    L.append(f"#define CONFIG_IRQ_STACK   {_bool(cfg, 'IRQ_STACK')}")
    L.append(f"#define CONFIG_NMI_ENABLE  {_bool(cfg, 'NMI_ENABLE')}")

    L += ["", "/* ---- USB ---- */"]
    L.append(f"#define CONFIG_USB_ENABLE  {_bool(cfg, 'USB_ENABLE')}")
    L.append(f"#define CONFIG_USB_XHCI    {_bool(cfg, 'USB_XHCI')}")
    L.append(f"#define CONFIG_USB_EHCI    {_bool(cfg, 'USB_EHCI')}")
    L.append(f"#define CONFIG_USB_UHCI    {_bool(cfg, 'USB_UHCI')}")
    L.append(f"#define CONFIG_USB_HID     {_bool(cfg, 'USB_HID')}")

    L += ["", "/* ---- Storage ---- */"]
    L.append(f"#define CONFIG_ATA_ENABLE    {_bool(cfg, 'ATA_ENABLE')}")
    L.append(f"#define CONFIG_SATA_ENABLE   {_bool(cfg, 'SATA_ENABLE')}")
    L.append(f"#define CONFIG_SD_ENABLE     {_bool(cfg, 'SD_ENABLE')}")
    L.append(f"#define CONFIG_FAT32_ENABLE  {_bool(cfg, 'FAT32_ENABLE')}")
    L.append(f"#define CONFIG_RAMFS_ENABLE  {_bool(cfg, 'RAMFS_ENABLE')}")
    L.append(f"#define CONFIG_VFS_ENABLE    {_bool(cfg, 'VFS_ENABLE')}")
    L.append(f"#define CONFIG_ZIP_ENABLE    {_bool(cfg, 'ZIP_ENABLE')}")
    L.append(f"#define CONFIG_ATA_DMA       {_bool(cfg, 'ATA_DMA')}")

    L += ["", "/* ---- Networking ---- */"]
    L.append(f"#define CONFIG_NET_ENABLE    {_bool(cfg, 'NET_ENABLE')}")
    L.append(f"#define CONFIG_E1000_ENABLE  {_bool(cfg, 'E1000_ENABLE')}")
    L.append(f"#define CONFIG_E100_ENABLE   {_bool(cfg, 'E100_ENABLE')}")
    L.append(f"#define CONFIG_IP_ENABLE     {_bool(cfg, 'IP_ENABLE')}")
    L.append(f"#define CONFIG_UDP_ENABLE    {_bool(cfg, 'UDP_ENABLE')}")
    L.append(f"#define CONFIG_TCP_ENABLE    {_bool(cfg, 'TCP_ENABLE')}")

    L += ["", "/* ---- Audio ---- */"]
    L.append(f"#define CONFIG_AUDIO_ENABLE  {_bool(cfg, 'AUDIO_ENABLE')}")
    L.append(f"#define CONFIG_AC97_ENABLE   {_bool(cfg, 'AC97_ENABLE')}")
    L.append(f"#define CONFIG_HDA_ENABLE    {_bool(cfg, 'HDA_ENABLE')}")

    L += ["", "/* ---- HID ---- */"]
    L.append(f"#define CONFIG_KBD_ENABLE    {_bool(cfg, 'KBD_ENABLE')}")
    L.append(f"#define CONFIG_MOUSE_ENABLE  {_bool(cfg, 'MOUSE_ENABLE')}")
    L.append(f"#define CONFIG_TOUCH_ENABLE  {_bool(cfg, 'TOUCH_ENABLE')}")

    L += ["", "/* ---- GPU ---- */"]
    L.append(f"#define CONFIG_GPU_ENABLE    {_bool(cfg, 'GPU_ENABLE')}")
    L.append(f"#define CONFIG_VESA_ENABLE   {_bool(cfg, 'VESA_ENABLE')}")

    L += ["", "/* ---- PCI ---- */"]
    L.append(f"#define CONFIG_PCI_ENABLE    {_bool(cfg, 'PCI_ENABLE')}")
    L.append(f"#define CONFIG_PCI_PROBE_ALL {_bool(cfg, 'PCI_PROBE_ALL')}")

    L += ["", "/* ---- Scheduler ---- */"]
    L.append(f"#define CONFIG_SCHED_ENABLE         {_bool(cfg, 'SCHED_ENABLE')}")
    L.append(f"#define CONFIG_SCHED_PREEMPT        {_bool(cfg, 'SCHED_PREEMPT')}")
    L.append(f"#define CONFIG_SCHED_TIMESLICE_MS   {_int(cfg, 'SCHED_TIMESLICE_MS', 10)}")

    L += ["", "/* ---- Syscalls ---- */"]
    L.append(f"#define CONFIG_SYSCALL_ENABLE  {_bool(cfg, 'SYSCALL_ENABLE')}")
    L.append(f"#define CONFIG_ELF_LOADER      {_bool(cfg, 'ELF_LOADER')}")

    L += ["", "/* ---- Debugging ---- */"]
    L.append(f"#define CONFIG_DEBUG_VERBOSE    {_bool(cfg, 'DEBUG_VERBOSE')}")
    L.append(f"#define CONFIG_DEBUG_KASAN      {_bool(cfg, 'DEBUG_KASAN')}")
    L.append(f"#define CONFIG_DEBUG_PANIC_DUMP {_bool(cfg, 'DEBUG_PANIC_DUMP')}")

    L += ["", "/* ---- QEMU defaults (for Makefile passthrough) ---- */"]
    L.append(f"#define CONFIG_QEMU_RAM_MB     {_int(cfg, 'QEMU_RAM_MB', 256)}")
    L.append(f"#define CONFIG_QEMU_SMP        {_int(cfg, 'QEMU_SMP', 1)}")
    L.append(f"#define CONFIG_QEMU_NET        {_bool(cfg, 'QEMU_NET')}")
    L.append(f"#define CONFIG_QEMU_USB        {_bool(cfg, 'QEMU_USB')}")
    L.append(f"#define CONFIG_QEMU_NOGRAPHIC  {_bool(cfg, 'QEMU_NOGRAPHIC')}")
    L.append("")

    os.makedirs(os.path.dirname(sys.argv[2]), exist_ok=True)
    with open(sys.argv[2], "w", encoding="utf-8") as f:
        f.write("\n".join(L))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
