#!/usr/bin/env python3
"""
scripts/gen_kconfig_h.py — Generate include/ark/kconfig.h from .kconfig
"""
from __future__ import annotations
import os, sys

DEFAULTS: dict[str, str] = {
    "ARCH": "x86_64", "BITS": "64", "CODENAME": "affectionate-cat",
    "OPT_LEVEL": "2", "DEBUG": "0", "WERROR": "0",
    "INIT_BIN": "/init", "BUILD_INIT": "0",
    "PRINTK_ENABLE": "1", "SERIAL_ENABLE": "1",
    "SERIAL_PORT": "0x3F8", "LOGLEVEL": "4",
    "PMM_ENABLE": "1", "VMM_ENABLE": "1",
    "HEAP_SIZE_KB": "4096", "STACK_SIZE_KB": "64",
    "FB_ENABLE": "1", "FB_WIDTH": "1024", "FB_HEIGHT": "768",
    "FB_BPP": "32", "FB_DRIVER": "bga",
    "PIO_ENABLE": "1", "MMIO_ENABLE": "1",
    "IOAPIC_ENABLE": "1", "PIC_ENABLE": "1",
    "IDT_ENABLE": "1", "IRQ_STACK": "1", "NMI_ENABLE": "1",
    "USB_ENABLE": "1", "USB_XHCI": "1", "USB_EHCI": "1",
    "USB_UHCI": "0", "USB_HID": "1",
    "ATA_ENABLE": "1", "ATA_DMA": "1", "SATA_ENABLE": "1",
    "SD_ENABLE": "1", "FAT32_ENABLE": "1", "RAMFS_ENABLE": "1",
    "AFS_ENABLE": "1", "AFS_GPT": "1", "AFS_MBR": "1",
    "VFS_ENABLE": "1", "ZIP_ENABLE": "1",
    "NET_ENABLE": "1", "E1000_ENABLE": "1", "E100_ENABLE": "0",
    "IP_ENABLE": "1", "UDP_ENABLE": "1", "TCP_ENABLE": "0",
    "AUDIO_ENABLE": "1", "AC97_ENABLE": "1", "HDA_ENABLE": "0",
    "KBD_ENABLE": "1", "MOUSE_ENABLE": "1", "TOUCH_ENABLE": "0",
    "GPU_ENABLE": "1", "VESA_ENABLE": "1",
    "PCI_ENABLE": "1", "PCI_PROBE_ALL": "1",
    "SCHED_ENABLE": "1", "SCHED_PREEMPT": "1", "SCHED_TIMESLICE_MS": "10",
    "SCHED_MAX_TASKS": "64", "SCHED_STACK_KB": "16", "SCHED_JOB_CONTROL": "1", "SCHED_PIT_HZ": "100",
    "SYSCALL_ENABLE": "1", "ELF_LOADER": "1",
    "DEBUG_VERBOSE": "0", "DEBUG_KASAN": "0", "DEBUG_PANIC_DUMP": "1",
    "ZIG_ENABLE": "0",
}

def _q(s): return '"' + s.replace("\\","\\\\").replace('"','\\"') + '"'
def _b(cfg, k):
    v = cfg.get(k, DEFAULTS.get(k, "0"))
    try:    return 1 if int(v, 0) else 0
    except: return 1 if str(v).lower() in ("y","yes","true","1") else 0
def _i(cfg, k, d=0):
    v = cfg.get(k, DEFAULTS.get(k, str(d)))
    try:    return int(v, 0)
    except: return d

def read_kv(path):
    cfg = dict(DEFAULTS)
    if not os.path.exists(path): return cfg
    with open(path, encoding="utf-8", errors="replace") as f:
        for raw in f:
            line = raw.strip()
            if not line or line.startswith("#") or "=" not in line: continue
            k, v = line.split("=", 1)
            k, v = k.strip(), v.strip()
            if k: cfg[k] = v
    return cfg

def main():
    if len(sys.argv) != 3:
        print("usage: gen_kconfig_h.py <.kconfig> <out.h>", file=sys.stderr)
        return 2
    cfg  = read_kv(sys.argv[1])
    arch = cfg.get("ARCH", "x86").strip()
    bits = 64 if arch == "x86_64" else 32
    L = [
        "/* Auto-generated by scripts/gen_kconfig_h.py — DO NOT EDIT. */",
        "#pragma once", "",
        "/* Architecture */",
        f"#define CONFIG_ARCH          {_q(arch)}",
        f"#define CONFIG_BITS          {bits}",
        f"#define CONFIG_32BIT         {1 if bits==32 else 0}",
        f"#define CONFIG_64BIT         {1 if bits==64 else 0}",
    ]
    for a in ("x86","x86_64"):
        L.append(f"#define CONFIG_ARCH_{a.upper():<12} {1 if arch==a else 0}")

    L += ["", "/* Build */",
        f"#define CONFIG_OPT_LEVEL     {_i(cfg,'OPT_LEVEL',2)}",
        f"#define CONFIG_DEBUG         {_b(cfg,'DEBUG')}",
        f"#define CONFIG_WERROR        {_b(cfg,'WERROR')}",
        f"#define CONFIG_CODENAME      {_q(cfg.get('CODENAME','ark'))}",
        f"#define CONFIG_INIT_BIN      {_q(cfg.get('INIT_BIN','/init'))}",
    ]
    L += ["", "/* Printk / Serial */",
        f"#define CONFIG_PRINTK_ENABLE {_b(cfg,'PRINTK_ENABLE')}",
        f"#define CONFIG_SERIAL_ENABLE {_b(cfg,'SERIAL_ENABLE')}",
        f"#define CONFIG_SERIAL_PORT   {_i(cfg,'SERIAL_PORT',0x3F8)}",
        f"#define CONFIG_LOGLEVEL      {_i(cfg,'LOGLEVEL',4)}",
    ]
    L += ["", "/* Memory */",
        f"#define CONFIG_PMM_ENABLE    {_b(cfg,'PMM_ENABLE')}",
        f"#define CONFIG_VMM_ENABLE    {_b(cfg,'VMM_ENABLE')}",
        f"#define CONFIG_HEAP_SIZE_KB  {_i(cfg,'HEAP_SIZE_KB',4096)}",
        f"#define CONFIG_STACK_SIZE_KB {_i(cfg,'STACK_SIZE_KB',64)}",
    ]
    L += ["", "/* Framebuffer */",
        f"#define CONFIG_FB_ENABLE     {_b(cfg,'FB_ENABLE')}",
        f"#define CONFIG_FB_WIDTH      {_i(cfg,'FB_WIDTH',1024)}",
        f"#define CONFIG_FB_HEIGHT     {_i(cfg,'FB_HEIGHT',768)}",
        f"#define CONFIG_FB_BPP        {_i(cfg,'FB_BPP',32)}",
        f"#define CONFIG_FB_DRIVER     {_q(cfg.get('FB_DRIVER','bga'))}",
    ]
    L += ["", "/* I/O */",
        f"#define CONFIG_PIO_ENABLE    {_b(cfg,'PIO_ENABLE')}",
        f"#define CONFIG_MMIO_ENABLE   {_b(cfg,'MMIO_ENABLE')}",
        f"#define CONFIG_IOAPIC_ENABLE {_b(cfg,'IOAPIC_ENABLE')}",
        f"#define CONFIG_PIC_ENABLE    {_b(cfg,'PIC_ENABLE')}",
    ]
    L += ["", "/* Interrupts */",
        f"#define CONFIG_IDT_ENABLE    {_b(cfg,'IDT_ENABLE')}",
        f"#define CONFIG_IRQ_STACK     {_b(cfg,'IRQ_STACK')}",
        f"#define CONFIG_NMI_ENABLE    {_b(cfg,'NMI_ENABLE')}",
    ]
    L += ["", "/* USB */",
        f"#define CONFIG_USB_ENABLE    {_b(cfg,'USB_ENABLE')}",
        f"#define CONFIG_USB_XHCI      {_b(cfg,'USB_XHCI')}",
        f"#define CONFIG_USB_EHCI      {_b(cfg,'USB_EHCI')}",
        f"#define CONFIG_USB_UHCI      {_b(cfg,'USB_UHCI')}",
        f"#define CONFIG_USB_HID       {_b(cfg,'USB_HID')}",
    ]
    L += ["", "/* Storage */",
        f"#define CONFIG_ATA_ENABLE    {_b(cfg,'ATA_ENABLE')}",
        f"#define CONFIG_ATA_DMA       {_b(cfg,'ATA_DMA')}",
        f"#define CONFIG_SATA_ENABLE   {_b(cfg,'SATA_ENABLE')}",
        f"#define CONFIG_SD_ENABLE     {_b(cfg,'SD_ENABLE')}",
        f"#define CONFIG_FAT32_ENABLE  {_b(cfg,'FAT32_ENABLE')}",
        f"#define CONFIG_RAMFS_ENABLE  {_b(cfg,'RAMFS_ENABLE')}",
        f"#define CONFIG_AFS_ENABLE    {_b(cfg,'AFS_ENABLE')}",
        f"#define CONFIG_AFS_GPT       {_b(cfg,'AFS_GPT')}",
        f"#define CONFIG_AFS_MBR       {_b(cfg,'AFS_MBR')}",
        f"#define CONFIG_VFS_ENABLE    {_b(cfg,'VFS_ENABLE')}",
        f"#define CONFIG_ZIP_ENABLE    {_b(cfg,'ZIP_ENABLE')}",
    ]
    L += ["", "/* Networking */",
        f"#define CONFIG_NET_ENABLE    {_b(cfg,'NET_ENABLE')}",
        f"#define CONFIG_E1000_ENABLE  {_b(cfg,'E1000_ENABLE')}",
        f"#define CONFIG_E100_ENABLE   {_b(cfg,'E100_ENABLE')}",
        f"#define CONFIG_IP_ENABLE     {_b(cfg,'IP_ENABLE')}",
        f"#define CONFIG_UDP_ENABLE    {_b(cfg,'UDP_ENABLE')}",
        f"#define CONFIG_TCP_ENABLE    {_b(cfg,'TCP_ENABLE')}",
    ]
    L += ["", "/* Audio */",
        f"#define CONFIG_AUDIO_ENABLE  {_b(cfg,'AUDIO_ENABLE')}",
        f"#define CONFIG_AC97_ENABLE   {_b(cfg,'AC97_ENABLE')}",
        f"#define CONFIG_HDA_ENABLE    {_b(cfg,'HDA_ENABLE')}",
    ]
    L += ["", "/* HID */",
        f"#define CONFIG_KBD_ENABLE    {_b(cfg,'KBD_ENABLE')}",
        f"#define CONFIG_MOUSE_ENABLE  {_b(cfg,'MOUSE_ENABLE')}",
        f"#define CONFIG_TOUCH_ENABLE  {_b(cfg,'TOUCH_ENABLE')}",
    ]
    L += ["", "/* GPU */",
        f"#define CONFIG_GPU_ENABLE    {_b(cfg,'GPU_ENABLE')}",
        f"#define CONFIG_VESA_ENABLE   {_b(cfg,'VESA_ENABLE')}",
    ]
    L += ["", "/* PCI */",
        f"#define CONFIG_PCI_ENABLE    {_b(cfg,'PCI_ENABLE')}",
        f"#define CONFIG_PCI_PROBE_ALL {_b(cfg,'PCI_PROBE_ALL')}",
    ]
    L += ["", "/* Scheduler */",
        f"#define CONFIG_SCHED_ENABLE        {_b(cfg,'SCHED_ENABLE')}",
        f"#define CONFIG_SCHED_PREEMPT       {_b(cfg,'SCHED_PREEMPT')}",
        f"#define CONFIG_SCHED_TIMESLICE_MS  {_i(cfg,'SCHED_TIMESLICE_MS',10)}",
        f"#define CONFIG_SCHED_MAX_TASKS     {_i(cfg,'SCHED_MAX_TASKS',64)}",
        f"#define CONFIG_SCHED_STACK_KB      {_i(cfg,'SCHED_STACK_KB',16)}",
        f"#define CONFIG_SCHED_JOB_CONTROL   {_b(cfg,'SCHED_JOB_CONTROL')}",
        f"#define CONFIG_SCHED_PIT_HZ        {_i(cfg,'SCHED_PIT_HZ',100)}",
    ]
    L += ["", "/* Syscalls */",
        f"#define CONFIG_SYSCALL_ENABLE {_b(cfg,'SYSCALL_ENABLE')}",
        f"#define CONFIG_ELF_LOADER     {_b(cfg,'ELF_LOADER')}",
    ]
    L += ["", "/* Debugging */",
        f"#define CONFIG_DEBUG_VERBOSE    {_b(cfg,'DEBUG_VERBOSE')}",
        f"#define CONFIG_DEBUG_KASAN      {_b(cfg,'DEBUG_KASAN')}",
        f"#define CONFIG_DEBUG_PANIC_DUMP {_b(cfg,'DEBUG_PANIC_DUMP')}",
    ]
    L += ["", "/* Zig */",
        f"#define CONFIG_ZIG_ENABLE      {_b(cfg,'ZIG_ENABLE')}",
        "",
    ]
    os.makedirs(os.path.dirname(sys.argv[2]), exist_ok=True)
    with open(sys.argv[2], "w", encoding="utf-8") as f:
        f.write("\n".join(L))
    return 0

if __name__ == "__main__":
    raise SystemExit(main())
