/* Auto-generated by scripts/gen_kconfig_h.py — DO NOT EDIT. */
#pragma once

/* Architecture */
#define CONFIG_ARCH          "x86_64"
#define CONFIG_BITS          64
#define CONFIG_32BIT         0
#define CONFIG_64BIT         1
#define CONFIG_ARCH_X86          0
#define CONFIG_ARCH_X86_64       1

/* Build */
#define CONFIG_OPT_LEVEL     2
#define CONFIG_DEBUG         1
#define CONFIG_WERROR        1
#define CONFIG_CODENAME      "allyes"
#define CONFIG_INIT_BIN      "/init"

/* Printk / Serial */
#define CONFIG_PRINTK_ENABLE 1
#define CONFIG_SERIAL_ENABLE 1
#define CONFIG_SERIAL_PORT   1016
#define CONFIG_LOGLEVEL      7

/* Memory */
#define CONFIG_PMM_ENABLE    1
#define CONFIG_VMM_ENABLE    1
#define CONFIG_HEAP_SIZE_KB  4096
#define CONFIG_STACK_SIZE_KB 64

/* Framebuffer */
#define CONFIG_FB_ENABLE     1
#define CONFIG_FB_WIDTH      1024
#define CONFIG_FB_HEIGHT     768
#define CONFIG_FB_BPP        32
#define CONFIG_FB_DRIVER     "bga"

/* I/O */
#define CONFIG_PIO_ENABLE    1
#define CONFIG_MMIO_ENABLE   1
#define CONFIG_IOAPIC_ENABLE 1
#define CONFIG_PIC_ENABLE    1

/* Interrupts */
#define CONFIG_IDT_ENABLE    1
#define CONFIG_IRQ_STACK     1
#define CONFIG_NMI_ENABLE    1

/* USB */
#define CONFIG_USB_ENABLE    1
#define CONFIG_USB_XHCI      1
#define CONFIG_USB_EHCI      1
#define CONFIG_USB_UHCI      1
#define CONFIG_USB_HID       1

/* Storage */
#define CONFIG_ATA_ENABLE    1
#define CONFIG_ATA_DMA       1
#define CONFIG_SATA_ENABLE   1
#define CONFIG_SD_ENABLE     1
#define CONFIG_FAT32_ENABLE  1
#define CONFIG_RAMFS_ENABLE  1
#define CONFIG_AFS_ENABLE    1
#define CONFIG_AFS_GPT       1
#define CONFIG_AFS_MBR       1
#define CONFIG_VFS_ENABLE    1
#define CONFIG_ZIP_ENABLE    1

/* Networking */
#define CONFIG_NET_ENABLE    1
#define CONFIG_E1000_ENABLE  1
#define CONFIG_E100_ENABLE   1
#define CONFIG_IP_ENABLE     1
#define CONFIG_UDP_ENABLE    1
#define CONFIG_TCP_ENABLE    1

/* Audio */
#define CONFIG_AUDIO_ENABLE  1
#define CONFIG_AC97_ENABLE   1
#define CONFIG_HDA_ENABLE    1

/* HID */
#define CONFIG_KBD_ENABLE    1
#define CONFIG_MOUSE_ENABLE  1
#define CONFIG_TOUCH_ENABLE  1

/* GPU */
#define CONFIG_GPU_ENABLE    1
#define CONFIG_VESA_ENABLE   1

/* PCI */
#define CONFIG_PCI_ENABLE    1
#define CONFIG_PCI_PROBE_ALL 1

/* Scheduler */
#define CONFIG_SCHED_ENABLE        1
#define CONFIG_SCHED_PREEMPT       1
#define CONFIG_SCHED_TIMESLICE_MS  10
#define CONFIG_SCHED_MAX_TASKS     64
#define CONFIG_SCHED_STACK_KB      16
#define CONFIG_SCHED_JOB_CONTROL   1
#define CONFIG_SCHED_PIT_HZ        100

/* Syscalls */
#define CONFIG_SYSCALL_ENABLE 1
#define CONFIG_ELF_LOADER     1

/* Debugging */
#define CONFIG_DEBUG_VERBOSE    1
#define CONFIG_DEBUG_KASAN      1
#define CONFIG_DEBUG_PANIC_DUMP 1

/* Zig */
#define CONFIG_ZIG_ENABLE      1
